### ISSUE TITLE
a bug in the OTS GUI configuration editor:

### ISSUE THREAD

**Issue by pavel1murat** [art-daq/otsdaq#100]
- according to the config editor GUI, the chosen config group has number 88 (this is what I did manually after taking a run and transitioning to the HALT state -  I activated the TrkVstAnnexConfig group v88).

- however to configure the next run the state machine uses the config group number 89 - confirmed by looking at the generated FCL's

![image](https://github.com/art-daq/otsdaq/assets/6231321/be2c6bb5-bbc4-4cee-b074-9d30d59406a1)

**Comment by eflumerf** [comment]
I'm looking at the "Editor Configuration:" line, and it appears that the "trk_vst_annex_config" alias is not assigned to TrkVstAnnexConfig(88)...my guess is that the state machine is doing the "correct" thing by running TrkVstAnnexConfig(89), which has the alias "trk_vst_annex_config".

**Comment by pavel1murat** [comment]
this seems to be yet another undocumented feature of the GUI which doesn't allow to activate ANY configuration. 
* it looks that one can activate only a configuration which has an alias, but as it is not documented, I'm just guessing here.
