### ISSUE TITLE
Add ability to diff two table versions

### ISSUE THREAD

**Issue by eflumerf** [art-daq/otsdaq#12]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/16902 (FNAL account required)*
*Originally created by @rrivera747 on 2017-06-19 19:41:41*

----

An ability to compare the current version with another might be useful to someone.

**Comment by eflumerf** [comment]
@rrivera747 Status?

**Comment by rrivera747** [comment]
This feature is fully functional with pull request #124
