### ISSUE TITLE
Add Tree-View Filter flexibility

### ISSUE THREAD

**Issue by eflumerf** [art-daq/otsdaq#14]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/16905 (FNAL account required)*
*Originally created by @rrivera747 on 2017-06-19 19:48:56*

----

Add & or | to filter tree view function applyTreeFilter() in ConfigurationGUI js .. similar to Configuration Group alias name filter in C++ of Supervisor

**Comment by eflumerf** [comment]
@rrivera747 Status?

**Comment by rrivera747** [comment]
Added | to tree view filter in otsdaq-utilities PR  #99 https://github.com/art-daq/otsdaq_utilities/pull/99

& is basically already implemented as part of * wildcard usage.
