### ISSUE TITLE
Feature for Tree-view Extraneous info

### ISSUE THREAD

**Issue by eflumerf** [art-daq/otsdaq#23]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/16917 (FNAL account required)*
*Originally created by @rrivera747 on 2017-06-19 20:09:07*

----

Identify tables that don’t link to any tables and are not linked to themselves and point them out when doing tree-view.
>This could help people simplify groups or delete tables

**Comment by rrivera747** [comment]
Orphaned table warnings are implemented in the Tree View in otsdaq-utilities PR #99 https://github.com/art-daq/otsdaq_utilities/pull/99
