### ISSUE TITLE
Indicator for "Dirty" values in Config Tree, Groups, and Tables

### ISSUE THREAD

**Issue by eflumerf** [art-daq/otsdaq#41]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/17696 (FNAL account required)*
*Originally created by @rrivera747 on 2017-09-12 19:47:09*

----

In all views (tree, groups, tables), .. stealing from the ideas in Kurt's test bench DAQ notes, the views should indicate in some way the "dirty" (i.e. changed since last save) values.

**Comment by rrivera747** [comment]
This feature is fully functional in pull request #124
