### ISSUE TITLE
Indicate Stale Data in Visualizer

### ISSUE THREAD

**Issue by eflumerf** [art-daq/otsdaq#56]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/20093 (FNAL account required)*
*Originally created by @rrivera747 on 2018-06-05 18:56:21*

----

If updating and data is not changing, change color of something to indicate that data has not changed.. this would be helpful when histogram shape is not changing much - it's hard to tell if data is still coming or if something is stuck.

**Comment by rrivera747** [comment]
This feature is fully functional with pull request #124
