### ISSUE TITLE
Update reset_ots_snapshot.sh and scripts it uses

### ISSUE THREAD

**Issue by eflumerf** [art-daq/otsdaq#72]
We will probably want to use experiment-specific locations for snapshots, which may be hosted on the open web. The "demo" now uses https://github.com/art-daq/otsdaq_demo_data, but that shouldn't be used for snapshots. It's possible that Mu2e, for instance, could start using specific tags of their config repo as snapshots, but we should think about how to manage this from the central scripts.

**Comment by rrivera747** [comment]
An example of this feature implemented for Mu2e can be found here: https://github.com/Mu2e/otsdaq_mu2e/blob/develop/tools/reset_mu2e_ots_snapshot.sh
