### ISSUE TITLE
OTS GUI woes

### ISSUE THREAD

**Issue by pavel1murat** [art-daq/otsdaq#99]
it would be nice to have the printout  in the view below wrapped around to avoid the horizontal scrolling

![image](https://github.com/art-daq/otsdaq/assets/6231321/2e448b9a-a87e-4c6d-8630-54f9c35868cf)
![image](https://github.com/art-daq/otsdaq/assets/6231321/2019c721-bf00-4f34-b726-d77ffa61cf15)

**Comment by rrivera747** [comment]
Issue addressed by Pull Request #112
